### PR TITLE
AFC, mp3 files appending and some fixes for unstable

### PR DESCRIPTION
**Pull request by mister-r**
AFC, mp3 files appending and some fixes
BTW didn't test with NFM ..

### CODE REVIEW

**Comment by szpajder** [comment]
I tested it with NFM. Works OK.

I like the append option. How about making it on by default?

However I find the tones a bit too obtrusive. I would prefer something shorter (like three 2 kHz 100ms beeps separated with 25 ms of silence) and quieter (eg. 0.9 * max_amplitude). Additionally, when continuous recording is off, it would be better to emit only one sequence of beeps instead of two. What do you think?

For floats, we should use sinf(), not sin(), right?

**Comment by mister-r** [comment]
default: I prefer making new features no-default. Also there is a risk of generating one year of silence in case of system clock goes wrong for one year :)
tones: I selected them to ensure they distinguishable from any other potential sounds from air, so better leave them different freqs, however making them shorter not bad idea
sinf: definately more appropriate there, will change later

**Comment by szpajder** [comment]
But the recording itself is non-default (you have to define a file output to turn it on), and when you turn it on, the default mode is continuous=false, which would prevent any silence being inserted.

In order not to insert one year of silence you could simply cap its duration at one hour. Because recorded files get rotated every hour, you shouldn't be inserting any more silence into a file.

Overwriting a recording after program restart is quite nasty (it's data loss, after all). I planned to address this by suffixing the file name with a number (like TWR_YYYYMMDD_01.mp3, _02.mp3, _03.mp3, etc). However appending to the file is a better and simpler solution, I think.

**Comment by szpajder** [comment]
Merged into unstable, thanks!

**Pull request merged**
