### PR TITLE
Add squelch debug output file

### PR DESCRIPTION
**Pull request by charlie-foxtrot**
Addition on top of #226 that adds a config option to generate debug output files for each squelch object, then the file(s) can then be loaded / plotted.

For example, here is the signal and audio output:

Screen Shot 2021-02-08 at 6 42 49 AM

and plotting of the debug data:

Screen Shot 2021-02-08 at 6 38 52 AM

Screen Shot 2021-02-08 at 6 38 54 AM

Screen Shot 2021-02-08 at 6 38 57 AM

### CODE REVIEW

**Comment by charlie-foxtrot** [comment]
Here is a comparison of this vs #226

https://github.com/charlie-foxtrot/RTLSDR-Airband/compare/refactor_squelch_update...charlie-foxtrot:squelch_debug

**Comment by szpajder** [comment]
The only person who benefits from this is the developer working on the squelch feature.

I also add such things while developing, but I strip them off before commiting. There is no point in exposing this in production code - if it's meant to be a feature, it requires documentation and maintenance later on, and this adds overhead.

**Comment by LoganSound** [comment]
Largely I agree with you but I'll tell you I'm using iNotifywait to trigger a screenshot of ADS-B traffic when a file concludes. There could be some other uses of correlating data to radio calls if squelch open were useable as a trigger!

**Comment by charlie-foxtrot** [comment]
@szpajder I wanted to include the code so others can leverage it and capture a debug file if/when they run into issues, but I understand not wanting it included for everyone.

I don't want to use the `DEBUG` ifdef's because that turns on additional logging that isnt necessary here (and slows things down).

I could add a `DEBUG_SQUELCH` option to the makefile and use that to ifndef out the code added here, would that address your concerns?

**Comment by szpajder** [comment]
Regardless of whether it is `#ifdef`'d or not, I consider the whole thing to be a temporary measure, at most.

However adding the `DEBUG_SQUELCH` macro would aid in stripping the debug code later on, before making a stable release.

**Comment by charlie-foxtrot** [comment]
`74834dd` switches to #ifdef instead of config file options.

@szpajder if you dont want to merge this PR I keep the debug code out of future PRs as well, but if someone has an issue with squelch they would need to move to another branch / fork to debug it.

**Review by szpajder — COMMENTED** [review]
I'll take it and decide later :)

**Pull request merged**
