### PR TITLE
Refactor squelch update

### PR DESCRIPTION
**Pull request by charlie-foxtrot**
This PR is based on #225 but makes cleanup that causes very minor diff.  For example shifting delay by 2 samples will increase/decrease squelch time and thereby the audio output by that number of samples.

My intent was to merge #225 first followed by this, so if anyone has a problem they could roll back to just after #225 merges to know if it was due to one of these minor changes or due to the refactoring in general.

With that said, it may be easier to review this PR rather than #225 (ie this doesn't have a bunch of TODO comments and throwaway code)

### CODE REVIEW

**Comment by starvald** [comment]
had it running about 10 hours with no issues so far.

**Comment by charlie-foxtrot** [comment]
I'm having some changes in channel bleed (ie the post-bandwidth squelching) that I wasn't expecting so hold off on merging this, but #225 is looking good

**Comment by szpajder** [comment]
I skipped #225 and I'm testing this one right now. Works well so far.

Can't comment on the channel bleed issue though, as I don't have any densely spaced channels that would be active at the same time.

**Comment by starvald** [comment]
same, marine band spacing is pretty wide.

**Comment by charlie-foxtrot** [comment]
Commit `dde2990` has the fix for cross channel bleed.  I also rolled back the noise floor update because it caused squelch to open too soon.

Turns out the current squelch code is quite good, even if I had no idea what it was doing ;)

With that said, im going to keep trying to make improvements.  Next step (under another PR) will be to try and and improve the flappy squelch.  First thought I had was to keep squelch open through the CLOSING phase and allow to go directly back to OPEN if there is still power (or power has returned).

This PR should be good to merge (please merge #225 first) and I'll open a new PR with actual improvements.

**Comment by charlie-foxtrot** [comment]
accidentally included a makefile change in `dde2990` that has been rolled back in `48fd9be`

**Pull request merged**
