### PR TITLE
Support splitting file by transmission

### PR DESCRIPTION
**Pull request by charlie-foxtrot**
create new config options for 'file' and 'rawfile':
 - include_freq: add the frequency in Hz to the end of the filename
 - split_on_transmission: create a file per "transmission" rather than one per hour

Rework struct file_data and file open/close logic to support split_on_transmission

### CODE REVIEW

**Comment by charlie-foxtrot** [comment]
Sample filenames for a `file` recording of 153.025 MHz on 6/21/2020 at 3:17:50 pm:

- standard: `dispatch_20200621_151750.mp3`
- split_on_transmission: `dispatch_20200621_151750.mp3`
- include_freq: `dispatch_20200621_151750_153025000.mp3`
- split_on_transmission and include_freq: `dispatch_20200621_151750_153025000.mp3`

@chuot please confirm these name formats will work for `Rdio Scanner`

**Comment by chuot** [comment]
@charlie-foxtrot I just did a test with your split_on_transmission branch and it work flawlessly. Great work!

However, time is zulu and I'm treating it as local. This will always be a problem, so I I will add a new `#ZTIME` meta tag for zulu time as opposed to `#TIME` which will stay for local time. I may also add `#MHZ` and `#KHZ` at the same time.
 
Here's the `dirWatch` I had on Rdio Scanner's side for testing:

```json
"dirWatch": [
  {
    "deleteAfter": true,
    "directory": "/home/radio/rtlsdr-airband/audio_files",
    "extension": "mp3",
    "system": 6,
    "talkgroup": 1,
    "mask": "TOWER_#DATE_#TIME_#HZ"
  }
]
```

**Comment by charlie-foxtrot** [comment]
@chuot excellent, im glad it worked!!

There is also a pre-existing `localtime` global option that can be set at the root of the `rtf_airband` config to switch it to local instead of GMT.  I don't see it in the wiki, but here's an example:

```
localtime = true;
fft_size = 1024;
devices:
(
...
```

**Comment by chuot** [comment]
@charlie-foxtrot I wasn't aware of this global option; it's nice to know, thanks!

**Comment by szpajder** [comment]
Great work @charlie-foxtrot, thanks!

**Comment by jonk6** [comment]
For what it's worth, I've been running  @charlie-foxtrot's split_on_transmission branch on both x86 and rpi4 for several days now and it definitely gets the job done.

**Comment by dc-to-daylight** [comment]
Thank you so much! This is so much cleaner than the hacky workaround I've been using!

Will build arm binaries for RP2B 👍

**Comment by chris021** [comment]
I have just had a play with this tonight and it is fantastic! Thank you @charlie-foxtrot !

While I fully understand the reason why this can't be used on a mixer, it does mean that Volume adjustments can't be made for quiet NFM files. Any suggestions on how to attack this?

**Comment by charlie-foxtrot** [comment]
@chris021 not sure I follow.  Are you asking for `ampfactor` to be supported on other mp3-based output types (ie `file` and `icecast`)?  If so, please open a new issue with the request.

**Comment by steve-horvath** [comment]
I'm not sure what I am doing wrong, but I don't get the frequency attached to the filename.
It scans correctly, and records all my channels, but there is no way to sort out what the source is so I can ingest it in to rdio-scanner, like I do with my multiple trunk systems.

I am running version RTLSDR-Airband version v3.2.1-2-gb4335d1

My config file:
`localtime=true;
log_scan_activity = true;
devices:
({
  type = "rtlsdr";
#  index = 2;
  serial = "77771111153705700";
  gain = 35;
  centerfreq = 120.0;
  correction = 1;
  mode = "scan";
  channels:
  (
    {
      freqs = ( 414.7125, 149.44, 150.575, 150.695, 148.885, 419.7625, 152.345, 154.07, 154.205, 154.16, 414.0375);
      modulation = "nfm";
      outputs: (
        {
        type = "file";
        directory = "/tmp/";
        filename_template = "Pagers";
        include_freq = true;
        split_on_transmission = true;
        }
      );
    }
  );
 }
);
`

**Pull request merged**
